
[[ec2-cloud-auto-discovery]]
==== EC2 Cloud Auto-Discovery

Hazelcast supports EC2 Auto Discovery. It is useful when you do not want or cannot provide the list of possible IP addresses. To configure your cluster to use EC2 Auto Discovery, disable join over multicast and TCP/IP, enable AWS, and provide your credentials (access and secret keys). 

You need to add the `hazelcast-cloud.jar` dependency to your project. Note that it is also bundled inside `hazelcast-all.jar`. The Hazelcast cloud module does not depend on any other third party modules.

To set your Hazelcast to EC2 Auto Discovery, set the following configuration elements. Refer to the <<aws-element, aws element section>> for the full description of the EC2 auto-discovery configuration elements.

- Set `multicast enabled` to "false".
- Set `tcp-ip enabled` to "false".
- Set `aws enabled` to "true".
- Set `access-key`, `secret-key`, `region`, etc. for your AWS values.

The following is an example declarative configuration.


```xml
<join>
  <multicast enabled="false">
  </multicast>
  <tcp-ip enabled="false">
  </tcp-ip>
  <aws enabled="true">
    <access-key>my-access-key</access-key>
    <secret-key>my-secret-key</secret-key>
    <region>us-west-1</region>
    <host-header>ec2.amazonaws.com</host-header>
    <security-group-name>hazelcast-sg</security-group-name>
    <tag-key>type</tag-key>
    <tag-value>hz-nodes</tag-value>
  </aws>
</join>
```

