[[set-configuration]]
=== Set Configuration

*_RELATED INFORMATION_*

_Please refer to <<set, Set>> to learn about the Hazelcast Distributed Set data structure._

The following are example set configurations.

[cols="5a,3a"]
|=========================
|Declarative|Programmatic

|
[source,xml]
----------
<set name="default">
   <backup-count>1</backup-count>
   <async-backup-count>0</async-backup-count>
   <max-size>10</max-size>
   <item-listeners>
      <item-listener>
          com.hazelcast.examples.ItemListener
      </item-listener>
   <item-listeners>
</set>
----------

|

[source,java]
--
Config config = new Config();
CollectionConfig collectionSet = config.getCollectionConfig();
collectionSet.setName( "MySet" ).setBackupCount( "1" )
        .setMaxSize( "10" );
--
|=========================


Set configuration has the following elements.


* `backup-count`: Count of synchronous backups. Set is a non-partitioned data structure, so all entries of a Set reside in one partition. When this parameter is '1', it means there will be 1 backup of that Set in another node in the cluster. When it is '2', 2 nodes will have the backup.
* `async-backup-count`: Count of asynchronous backups.
* `max-size`: The maximum number of entries for this Set.
* `item-listeners`: Lets you add listeners (listener classes) for the set items. You can also set the attributes `include-value` to `true` if you want the item event to contain the item values, and you can set `local` to `true` if you want to listen to the items on the local node.







