[[topic-configuration]]
=== Topic Configuration

*_RELATED INFORMATION_*

_Please refer to <<topic, Topic>> to learn about the Hazelcast Distributed Topic data structure._

The following are example topic configurations.

[cols="5a,3a"]
|=========================
|Declarative|Programmatic

|
[source,xml]
----------
<hazelcast>
  ...
  <topic name="yourTopicName">
    <global-ordering-enabled>true</global-ordering-enabled>
    <statistics-enabled>true</statistics-enabled>
    <message-listeners>
      <message-listener>MessageListenerImpl</message-listener>
    </message-listeners>
  </topic>
  ...
</hazelcast>
----------

|

[source,java]
--
TopicConfig topicConfig = new TopicConfig();
topicConfig.setGlobalOrderingEnabled( true );
topicConfig.setStatisticsEnabled( true );
topicConfig.setName( "yourTopicName" );
MessageListener<String> implementation = new MessageListener<String>() {
  @Override
  public void onMessage( Message<String> message ) {
    // process the message
  }
};
topicConfig.addMessageListenerConfig( new ListenerConfig( implementation ) );
HazelcastInstance instance = Hazelcast.newHazelcastInstance()
--
|=========================


Topic configuration has the following elements.

* `statistics-enabled`: Default is `true`, meaning statistics are calculated.
* `global-ordering-enabled`: Default is `false`, meaning there is no global order guarantee.
* `message-listeners`: Lets you add listeners (listener classes) for the topic messages.



Topic related but not topic specific configuration parameters

* `hazelcast.event.queue.capacity`: default value is 1,000,000.
* `hazelcast.event.queue.timeout.millis`: default value is 250.
* `hazelcast.event.thread.count`: default value is 5.

*_RELATED INFORMATION_* 

_For description of these parameters, please see <<global-event-configuration, Global Event Configuration>>._





