[[hazelcast-simulator]]
== Hazelcast Simulator

[[simulator-overview]]
=== Simulator Overview

Hazelcast Simulator is a production simulator used to test Hazelcast and Hazelcast-based applications in clustered environments. It also allows you to create your own tests and perform them on your Hazelcast clusters and applications that are deployed to cloud computing environments. In your tests, you can provide any property that can be specified on these environments (Amazon EC2, Google Compute Engine(GCE), or your own environment): properties such as hardware specifications, operating system, Java version, etc.

Hazelcast Simulator allows you to add potential production problems, such as real-life failures, network problems, overloaded CPU, and failing nodes to your tests. It also provides a benchmarking and performance testing platform by supporting performance tracking and also supporting various out-of-the-box profilers.

Hazelcast Simulator makes use of Apache jclouds(R), an open source multi-cloud toolkit that is primarily designed for testing on the clouds like Amazon EC2 and GCE.

You can use Hazelcast Simulator for the following use cases:

* In your pre-production phase to simulate the expected throughput/latency of Hazelcast with your specific requirements.
* To test if Hazelcast behaves as expected when you implement a new functionality in your project.
* As part of your test suite in your deployment process.
* When you upgrade your Hazelcast version.

Hazelcast Simulator is available as a downloadable package on the Hazelcast http://www.hazelcast.org/download[web site]. Please refer to the <<installing-simulator, Installing Simulator section>> for more information.
